# Generated by Django 5.1.1 on 2025-06-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Journey', max_length=255)),
                ('about', models.TextField()),
                ('project_count', models.IntegerField(default=5)),
                ('years_exp', models.IntegerField(default=1)),
                ('clients_count', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mohammad Rahish Shekh', max_length=255)),
                ('photo', models.ImageField(upload_to='profile_photo/')),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('title', models.CharField(default='Project Title', max_length=255)),
                ('desc', models.TextField()),
                ('tech_used', models.TextField()),
                ('git_link', models.CharField(default='git link', max_length=300)),
                ('live_link', models.CharField(default='live link', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('tech', models.CharField(default='django', max_length=255)),
                ('proficiency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SociAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='facebook', max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
