# Generated by Django 5.2.3 on 2025-06-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_project_created_at_skill_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about',
        ),
        migrations.AddField(
            model_name='about',
            name='about_p1',
            field=models.TextField(default='paragraph1'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_p2',
            field=models.TextField(default='paragraph2'),
        ),
    ]
