# Generated by Django 5.2.3 on 2025-06-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_remove_about_about_about_about_p1_about_about_p2'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
